bug fix:
- title: "Fix exception handling for correct xfailing on missing data for CYGNSS NetCDF reader"
  description: "Updated docstring for ``get_test_files``, replaced the ``FileNotFoundError`` with ``NameError`` to clearly indicate missing test data in ``cygnss_netcdf.py`` unit tests, and removed the corresponding ``except FileNotFoundError`` block in ``test_readers.py`` to allow the error to be raised properly."
  files:
    modified:
    - "geoips/plugins/modules/readers/cygnss_netcdf.py"
    - "tests/unit_tests_long/plugins/modules/readers/test_readers.py"
  related-issue:
    number: 873
    repo_url: ""
  date:
    start: "2025-01-31"
    finish: "2025-01-31"

